// File: src/theme/fonts.jsx
const fontType = {
    //PlusJakartaSans
    'Pjs-Bold': 'PlusJakartaSans-Bold',
    'Pjs-BoldItalic': 'PlusJakartaSans-BoldItalic',
    'Pjs-ExtraBold': 'PlusJakartaSans-ExtraBold',
    'Pjs-ExtraBoldItalic': 'PlusJakartaSans-ExtraBoldItalic',
    'Pjs-ExtraLight': 'PlusJakartaSans-ExtraLight',
    'Pjs-ExtraLightItalic': 'PlusJakartaSans-ExtraLightItalic',
    'Pjs-Italic': 'PlusJakartaSans-Italic',
    'Pjs-Light': 'PlusJakartaSans-Light',
    'Pjs-LightItalic': 'PlusJakartaSans-LightItalic',
    'Pjs-Medium': 'PlusJakartaSans-Medium',
    'Pjs-MediumItalic': 'PlusJakartaSans-MediumItalic',
    'Pjs-Regular': 'PlusJakartaSans-Regular',
    'Pjs-SemiBold': 'PlusJakartaSans-SemiBold',
    'Pjs-SemiBoldItalic': 'PlusJakartaSans-SemiBoldItalic',

    // OpenSans
    'Os-Bold': 'OpenSans-Bold',
    'Os-BoldItalic': 'OpenSans-BoldItalic',
    'Os-ExtraBold': 'OpenSans-ExtraBold',
    'Os-ExtraBoldItalic': 'OpenSans-ExtraBoldItalic',
    'Os-Italic': 'OpenSans-Italic',
    'Os-Light': 'OpenSans-Light',
    'Os-LightItalic': 'OpenSans-LightItalic',
    'Os-Regular': 'OpenSans-Regular',
    'Os-SemiBold': 'OpenSans-SemiBold',
    'Os-SemiBoldItalic': 'OpenSans-SemiBoldItalic',

    // Poppins
    'Pop-Black': 'Poppins-Black',
    'Pop-BlackItalic': 'Poppins-BlackItalic',
    'Pop-Bold': 'Poppins-Bold',
    'Pop-BoldItalic': 'Poppins-BoldItalic',
    'Pop-ExtraBold': 'Poppins-ExtraBold',
    'Pop-ExtraBoldItalic': 'Poppins-ExtraBoldItalic',
    'Pop-ExtraLight': 'Poppins-ExtraLight',
    'Pop-ExtraLightItalic': 'Poppins-ExtraLightItalic',
    'Pop-Italic': 'Poppins-Italic',
    'Pop-Light': 'Poppins-Light',
    'Pop-LightItalic': 'Poppins-LightItalic',
    'Pop-Medium': 'Poppins-Medium',
    'Pop-MediumItalic': 'Poppins-MediumItalic',
    'Pop-Regular': 'Poppins-Regular',
    'Pop-SemiBold': 'Poppins-SemiBold',
    'Pop-SemiBoldItalic': 'Poppins-SemiBoldItalic',
    'Pop-Thin': 'Poppins-Thin',
    'Pop-ThinItalic': 'Poppins-ThinItalic',

    // Roboto
    'Rob-Regular': 'Roboto-Regular',
    'Rob-Black': 'Roboto-Black',
    'Rob-BlackItalic': 'Roboto-BlackItalic',
    'Rob-Bold': 'Roboto-Bold',
    'Rob-BoldItalic': 'Roboto-BoldItalic',
    'Rob-Italic': 'Roboto-Italic',
    'Rob-Light': 'Roboto-Light',
    'Rob-LightItalic': 'Roboto-LightItalic',
    'Rob-Medium': 'Roboto-Medium',
    'Rob-MediumItalic': 'Roboto-MediumItalic',
    'Rob-Thin': 'Roboto-Thin',
    'Rob-ThinItalic': 'Roboto-ThinItalic',
};
export default fontType;